delete from module
insert into module values('m1', 'root',  '', '采购管理', '', 1)
--insert into module values('m11', 'm1',  'PurchasePlan', '采购计划', 'Purchase/Plan/Index', 1)
insert into module values('m12', 'm1',  'Purchase', '采购订单', 'Purchase/Index', 1)
insert into module values('m2', 'root',  '', '销售管理', '', 1)
insert into module values('m21', 'm2',  'Sale', '平台销售', 'Sale/Index', 1)
insert into module values('m22', 'm2',  'Store', '店铺销售', 'Store/Index', 1)
insert into module values('m3', 'root',  '', '仓库管理', '', 1)
insert into module values('m30', 'm3',  'StoreQuery', '库存查询', 'Store/Query/Index', 1)
insert into module values('m31', 'm3',  'Enter', '采购入库', 'Store/Enter/Index', 1)
insert into module values('m32', 'm3',  'PurchaseDelivery', '采购配送', 'Warehouse/Delivery/Purchase/Index', 1)
insert into module values('m33', 'm3',  'PurchaseReturn', '采购退货', 'Warehouse/Return/Purchase/Index', 1)
insert into module values('m34', 'm3',  'Exit', '销售出库', 'Store/Exit/Index', 1)
insert into module values('m35', 'm3',  'SaleDelivery', '销售配送', 'Warehouse/Delivery/Save/Index', 1)
insert into module values('m36', 'm3',  'SaleReturn', '销售退货', 'Warehouse/Return/Sale/Index', 1)
insert into module values('m37', 'm3',  'WarehouseCheck', '库存盘点', 'Warehouse/Check/Index', 1)
insert into module values('m38', 'm3',  'WarehouseScrap', '库存报损', 'Warehouse/Scrap/Index', 1)
insert into module values('m4', 'root',  '', '财务管理', '', 1)
insert into module values('m41', 'm4',  'Receivable', '应收账款', 'Account/Receivable/Index', 1)
insert into module values('m42', 'm4',  'Payable', '应付账款', 'Account/Payable/Index', 1)
insert into module values('m43', 'm4',  'Cost', '成本核算', 'Account/Cost/Index', 1)
insert into module values('m5', 'root',  '', '系统管理', '', 1)
insert into module values('m51', 'm5',  'Client', '客户管理', 'System/Client/Index', 1)
insert into module values('m52', 'm5',  'Item', '商品管理', 'System/Item/Index', 1)
insert into module values('m53', 'm5',  'Supply', '供应商管理', 'System/Supply/Index', 1)
insert into module values('m54', 'm5',  'Place', '货位管理', 'System/Place/Index', 1)
insert into module values('m55', 'm5',  'User', '用户管理', 'System/User/Index', 1)


