<?xml version="1.0" encoding="utf-8"?><Database Name="SupplyChainManager" Class="SupplyChainManagerDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=SupplyChainManager;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SupplyChainManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Office" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsHoliday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AgentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AgentBegin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgentEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Profile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CostCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reserve1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reserve2" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Reserve3" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Reserve4" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Module">
    <Type Name="Module">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ClientItem" Member="ClientItem">
    <Type Name="ClientItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MarketPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="ReturnDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExchangeDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RepairDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinOrderCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaleType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrepareDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplyType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TaxRate" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="IsOrder" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SupplyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dictionary" Member="Dictionary">
    <Type Name="Dictionary">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Module" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Field" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supply" Member="Supply">
    <Type Name="Supply">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BankNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Payment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentTerm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Item">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Wide" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="High" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="NetWeight" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BoxCount" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Producer" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Packages" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Guarantee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsGuarantee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsStoped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemStockView" Member="ItemStockView">
    <Type Name="ItemStockView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Wide" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="High" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="NetWeight" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BoxCount" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Producer" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Packages" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Guarantee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsGuarantee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsStoped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LimitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RealCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchase">
    <Type Name="Purchase">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SupplyType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateEnter" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EnterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeTax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FreightType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Invoice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExpectArrive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentTerm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateChecked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApproveId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproveName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateApproved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Purchase_PurchaseItem" Member="PurchaseItem" ThisKey="Id" OtherKey="PurchaseId" Type="PurchaseItem" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseItem" Member="PurchaseItem">
    <Type Name="PurchaseItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PurchaseNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Promotion" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountReal" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountMiss" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MissProcess" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Purchase_PurchaseItem" Member="Purchase" AccessModifier="Internal" ThisKey="PurchaseId" OtherKey="Id" Type="Purchase" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Client">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BankNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Payment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentTerm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClientStore" Member="ClientStore">
    <Type Name="ClientStore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sale" Member="Sale">
    <Type Name="Sale">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SaleType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ClientStore" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExitId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IncludeTax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FreightType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Invoice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PaymentTerm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateChecked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApproveId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApproveName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateApproved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Sale_SaleItem" Member="SaleItem" ThisKey="Id" OtherKey="SaleId" Type="SaleItem" />
    </Type>
  </Table>
  <Table Name="dbo.SaleItem" Member="SaleItem">
    <Type Name="SaleItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SaleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BatchNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateProduct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Promotion" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountReal" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountMiss" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MissProcess" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Sale_SaleItem" Member="Sale" AccessModifier="Internal" ThisKey="SaleId" OtherKey="Id" Type="Sale" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemBatchStockView" Member="ItemBatchStockView">
    <Type Name="ItemBatchStockView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Style" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Wide" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="High" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="NetWeight" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BoxCount" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Producer" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Packages" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Guarantee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsGuarantee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsStoped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LimitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateProduct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RealCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Enter" Member="Enter">
    <Type Name="Enter">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecordName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliverType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverContact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverTel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverPayType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverAmount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="CheckId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateChecked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Enter_EnterItem" Member="EnterItem" ThisKey="Id" OtherKey="EnterId" Type="EnterItem" />
    </Type>
  </Table>
  <Table Name="dbo.EnterItem" Member="EnterItem">
    <Type Name="EnterItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BatchNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateProduct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QuantityNeed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Enter_EnterItem" Member="Enter" AccessModifier="Internal" ThisKey="EnterId" OtherKey="Id" Type="Enter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseItemView" Member="PurchaseItemView">
    <Type Name="PurchaseItemView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PurchaseNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Promotion" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountReal" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountMiss" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MissProcess" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="SupplyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SupplyType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Exit]" Member="Exit">
    <Type Name="Exit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExitType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecordName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliverType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverContact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverTel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverPayType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeliverAmount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="CheckId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateChecked" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Exit_ExitItem" Member="ExitItem" ThisKey="Id" OtherKey="ExitId" Type="ExitItem" />
    </Type>
  </Table>
  <Table Name="dbo.ExitItem" Member="ExitItem">
    <Type Name="ExitItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExitId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BatchNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateProduct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QuantityNeed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Exit_ExitItem" Member="Exit" AccessModifier="Internal" ThisKey="ExitId" OtherKey="Id" Type="Exit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SaleItemView" Member="SaleItemView">
    <Type Name="SaleItemView">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SaleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StoreName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BatchNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateProduct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ItemNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Barcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Spec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Promotion" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityReal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountReal" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="QuantityMiss" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AmountMiss" Type="System.Decimal" DbType="Decimal(14,4)" CanBeNull="true" />
      <Column Name="MissProcess" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AddId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClientStore" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>